catalog_name: mlops_students
schema_name: cremerfederico29

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - lead_time
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - arrival_year
  - arrival_month
  - arrival_date
  - market_segment_type
  - repeated_guest

target: booking_status
