catalog_name: mlops_students
schema_name: cremerfederico29
pipeline_id: 26a1d95f-487c-45ed-8350-4d6964fd1053

id_field: Booking_ID

parameters:
  boosting_type: 'gbdt'
  num_leaves: 31
  max_depth: -1
  learning_rate: 0.1
  n_estimators: 100
  subsample: 1.0
  colsample_bytree: 1.0
  reg_alpha: 0.0
  reg_lambda: 0.0
  random_state: 42

ab_test:
  learning_rate_a: 0.01
  n_estimators_a: 100
  max_depth_a: 5
  learning_rate_b: 0.05
  n_estimators_b: 150
  max_depth_b: 7

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - lead_time
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - arrival_year
  - arrival_month
  - arrival_date
  - market_segment_type
  - repeated_guest

target: booking_status
